language: c

before_install:
  - wget http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl
  - export DEVKITPRO=/home/travis/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM

install:
  - sudo perl devkitARMupdate.pl  
  - wget --no-check-certificate https://codeload.github.com/smealum/ctrulib/zip/master -O /tmp/ctrulib.zip
  - unzip /tmp/ctrulib.zip
  - cd ctrulib-master/libctru
  - make && sudo make install
  - cd ../..
  - wget --no-check-certificate https://github.com/xerpi/3ds_portlibs/releases/download/1/portlibs-linux.zip -O /tmp/3ds_portlibs.zip
  - unzip /tmp/3ds_portlibs.zip
  - sudo cp -R portlibs ${DEVKITPRO}/
  - sudo apt-get --assume-yes install libpng-dev
  - sudo apt-get --assume-yes install zlib1g-dev
script:
  - echo "Starting compilation"  
  - make  
  - echo "Compilation ended"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libstdc++6
    - lftp